# Generated by Django 5.0.3 on 2024-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('image', models.JSONField(default=list)),
                ('brightness', models.IntegerField(default=100)),
                ('is_on', models.BooleanField(default=True)),
            ],
        ),
    ]
